import type { BlogPost } from './index'

export const post: BlogPost = {
  slug: 'ai-git-commits-vs-code',
  title: 'AI Commit Message Generators for VS Code: How They Work and Which to Use',
  description: 'A technical look at how AI commit message generators read your code changes and produce semantic commits. Includes comparison of VS Code extension options.',
  publishedAt: 'March 8, 2025',
  readTime: '6 min read',
  keywords: ['ai commit message generator', 'ai commit vscode', 'auto generate commit message', 'git commit ai', 'vscode commit extension'],
  content: [
    { type: 'p', content: 'AI commit message generators have matured significantly in the past two years. What started as basic tools that described file changes have become systems that understand the semantic meaning of code diffs — the difference between a change that adds a feature and one that fixes a regression.' },
    { type: 'h2', content: 'How AI Commit Generators Actually Work' },
    { type: 'p', content: 'The core technique is straightforward: read the git diff, send it to a language model, ask for a structured commit message. But the quality differences between tools come from the details.' },
    { type: 'h3', content: 'Reading the Diff' },
    { type: 'p', content: 'The best VS Code extensions use the VS Code git extension API directly, which means they read staged changes (git diff --cached) without needing to shell out to a subprocess:' },
    { type: 'code', content: '// VS Code Git API approach\nconst gitExtension = vscode.extensions.getExtension(\'vscode.git\')\nconst api = gitExtension.exports.getAPI(1)\nconst repo = api.repositories[0]\n\n// true = staged changes only (index diff)\nconst diff = await repo.diff(true)' },
    { type: 'p', content: 'This approach is more reliable than subprocess calls because it works consistently across operating systems and respects VS Code\'s authentication for private repositories.' },
    { type: 'h3', content: 'Choosing the Right Model' },
    { type: 'p', content: 'Not all language models are equally suited for commit message generation. The requirements are: fast response (you\'re waiting in your editor), structured output (needs to return JSON reliably), and genuine code understanding.' },
    { type: 'p', content: 'Claude Haiku is well-suited for this use case — it\'s fast enough for interactive use (under 2 seconds for typical diffs), reliably produces structured JSON output, and has strong understanding of code changes across all major programming languages.' },
    { type: 'h3', content: 'Prompt Engineering for Commit Messages' },
    { type: 'p', content: 'The prompt structure matters enormously. A good commit message generator prompt includes the diff, the branch name for context, the desired format (conventional commits, gitmoji, etc.), and explicit output format requirements:' },
    { type: 'code', content: 'Generate a Conventional Commits format git commit message.\n\nBranch: feature/oauth-login\nDiff:\n<diff content, truncated to 8KB>\n\nRespond with ONLY this JSON:\n{\n  "title": "feat(scope): description (max 72 chars)",\n  "bullets": ["change 1", "change 2"]\n}' },
    { type: 'h3', content: 'Handling Large Diffs' },
    { type: 'p', content: 'Large diffs are a real challenge. A 500-line refactor exceeds context windows and costs more to process. The pragmatic solution is truncation — take the first 8KB of the diff, which captures the most important changes in most cases. Truly massive changes that span entire modules may produce less accurate messages, but they\'re also the hardest for humans to summarize accurately anyway.' },
    { type: 'h2', content: 'VS Code Extensions for AI Commit Messages' },
    { type: 'p', content: 'Several VS Code extensions generate AI commit messages. They differ in approach, model choice, and UX:' },
    { type: 'h3', content: 'CommitCraft AI' },
    { type: 'p', content: 'VS Code extension with a dedicated panel UI. Reads staged diff via VS Code Git API, generates Conventional Commits using Claude Haiku, and fills the SCM input box on accept. Also generates PR descriptions and changelog entries. Free tier available.' },
    { type: 'h3', content: 'AI Commit (CLI tools)' },
    { type: 'p', content: 'Tools like aicommits and OpenCommit run in the terminal. They read the diff via git subprocess, call OpenAI\'s API, and print a message. You copy it manually. No VS Code integration — good if you prefer terminal-first workflows.' },
    { type: 'h2', content: 'What AI Gets Right (and Wrong)' },
    { type: 'p', content: 'AI commit generators are good at:' },
    { type: 'ul', content: [
      'Identifying the type of change (feat vs fix vs refactor)',
      'Finding the right scope from file paths and function names',
      'Summarizing multiple related changes into a coherent message',
      'Maintaining consistent format across all commits',
    ]},
    { type: 'p', content: 'They struggle with:' },
    { type: 'ul', content: [
      'Understanding business context (a fix might be a regression, not a bug fix)',
      'Monorepo scope attribution with very large diffs',
      'Generated code diffs that look like features but are actually auto-generated',
    ]},
    { type: 'p', content: 'The right posture is to treat AI-generated commits as a first draft. Review before accepting. Most of the time they\'re accurate. Occasionally they need a small correction. That\'s a much better starting point than "fix stuff".' },
    { type: 'cta', content: '' },
  ],
}
