import type { BlogPost } from './index'

export const post: BlogPost = {
  slug: 'conventional-commits-guide',
  title: 'Conventional Commits: A Complete Guide for Development Teams',
  description: 'Everything you need to know about Conventional Commits — the standard format for git commit messages adopted by thousands of teams. Includes all types, examples, tooling, and automation.',
  publishedAt: 'March 8, 2025',
  readTime: '8 min read',
  keywords: ['conventional commits', 'conventional commits format', 'semantic commits', 'git commit standard', 'commit types'],
  content: [
    { type: 'p', content: 'Conventional Commits is a specification for adding human and machine readable meaning to commit messages. It\'s simple, widely adopted, and solves the real problem of inconsistent commit history that makes code archaeology painful.' },
    { type: 'p', content: 'If your team hasn\'t adopted a commit message standard yet, Conventional Commits is the right choice. It\'s supported by tooling across every major language ecosystem, it\'s the format expected by most CI/CD systems that auto-generate changelogs, and it\'s what most open source projects use.' },
    { type: 'h2', content: 'The Conventional Commits Specification' },
    { type: 'p', content: 'The full format is:' },
    { type: 'code', content: '<type>[optional scope]: <description>\n\n[optional body]\n\n[optional footer(s)]' },
    { type: 'p', content: 'The type and description are required. Everything else is optional. The colon and space after the type are part of the format — don\'t skip them.' },
    { type: 'h2', content: 'All Commit Types — With When to Use Each' },
    { type: 'h3', content: 'feat — New Feature' },
    { type: 'p', content: 'Use for any commit that introduces a new feature or capability that didn\'t exist before. Maps to MINOR in Semantic Versioning.' },
    { type: 'code', content: 'feat(auth): add Google OAuth login\nfeat(api): add pagination to /users endpoint\nfeat: support dark mode in dashboard' },
    { type: 'h3', content: 'fix — Bug Fix' },
    { type: 'p', content: 'Use for commits that fix a bug in existing functionality. Maps to PATCH in Semantic Versioning.' },
    { type: 'code', content: 'fix(auth): clear refresh token on logout\nfix(api): handle null response from /users\nfix: prevent double-submit on checkout form' },
    { type: 'h3', content: 'docs — Documentation' },
    { type: 'p', content: 'Changes to documentation only — README, code comments, API docs. No code behavior changes.' },
    { type: 'code', content: 'docs(readme): add installation instructions for Windows\ndocs(api): document rate limiting headers\ndocs: fix typo in contributing guide' },
    { type: 'h3', content: 'style — Code Style' },
    { type: 'p', content: 'Formatting changes that don\'t affect behavior — whitespace, semicolons, line length. Running prettier counts as style.' },
    { type: 'code', content: 'style: run prettier on all TypeScript files\nstyle(components): fix inconsistent semicolons' },
    { type: 'h3', content: 'refactor — Code Restructure' },
    { type: 'p', content: 'Code changes that neither fix a bug nor add a feature. Extracting a function, renaming a variable, reorganizing file structure.' },
    { type: 'code', content: 'refactor(auth): extract token validation into separate module\nrefactor: move database config to environment module\nrefactor(api): simplify error handling middleware' },
    { type: 'h3', content: 'test — Tests' },
    { type: 'p', content: 'Adding missing tests, correcting existing tests, or refactoring tests. No production code changes.' },
    { type: 'code', content: 'test(auth): add unit tests for token refresh flow\ntest: increase coverage for API error handlers' },
    { type: 'h3', content: 'chore — Maintenance' },
    { type: 'p', content: 'Changes to build process, auxiliary tools, dependency updates. Doesn\'t modify src or test files.' },
    { type: 'code', content: 'chore(deps): upgrade React to 18.3.0\nchore: add .editorconfig\nchore(ci): update Node.js version to 20 in GitHub Actions' },
    { type: 'h3', content: 'perf — Performance' },
    { type: 'p', content: 'Changes that improve performance without changing behavior.' },
    { type: 'code', content: 'perf(db): add index on users.email for faster lookups\nperf(api): implement response caching for /products' },
    { type: 'h2', content: 'Using Scopes Effectively' },
    { type: 'p', content: 'The scope is a noun in parentheses describing the section of the codebase affected. It\'s optional but adds significant clarity in larger codebases.' },
    { type: 'p', content: 'Good scopes are:' },
    { type: 'ul', content: [
      'Module names: feat(auth):, fix(api):, refactor(db):',
      'Component names: style(Button):, feat(NavBar):',
      'Package names in monorepos: feat(web-app):, fix(shared-ui):',
    ]},
    { type: 'p', content: 'Avoid overly specific scopes that don\'t add value: fix(auth/services/TokenService/validateMethod) is worse than fix(auth).' },
    { type: 'h2', content: 'Breaking Changes' },
    { type: 'p', content: 'Breaking changes are indicated with an exclamation mark after the type/scope, or with a BREAKING CHANGE footer:' },
    { type: 'code', content: '# Method 1: exclamation mark\nfeat(api)!: change authentication header format\n\n# Method 2: footer\nfeat(api): change authentication header format\n\nBREAKING CHANGE: Authorization header now uses Bearer prefix.\nPrevious format: Authorization: <token>\nNew format: Authorization: Bearer <token>' },
    { type: 'h2', content: 'Tooling That Works With Conventional Commits' },
    { type: 'p', content: 'The real power of Conventional Commits comes from tooling built around the standard:' },
    { type: 'ul', content: [
      'commitlint — validates commit messages against the spec in CI',
      'semantic-release — automatically determines version bumps and generates changelogs',
      'standard-version — similar to semantic-release, simpler to configure',
      'release-please — Google\'s tool for automated GitHub releases from conventional commits',
      'CommitCraft AI — VS Code extension that generates conventional commits from your diff automatically',
    ]},
    { type: 'h2', content: 'Automating Conventional Commits With CommitCraft AI' },
    { type: 'p', content: 'The main friction with Conventional Commits is remembering the format and choosing the right type. CommitCraft AI eliminates that friction by reading your actual code changes and determining the appropriate type, scope, and description automatically.' },
    { type: 'cta', content: '' },
    { type: 'h2', content: 'Common Questions' },
    { type: 'h3', content: 'Should I use Conventional Commits for personal projects?' },
    { type: 'p', content: 'Yes, but the benefits are smaller. The main value is consistency across a team and automated tooling. For personal projects, the main benefit is that your git history will be readable when you come back to a project months later.' },
    { type: 'h3', content: 'What if I commit the wrong type?' },
    { type: 'p', content: 'If you haven\'t pushed: git commit --amend. If you have pushed and no one has pulled: git push --force-with-lease. If it\'s already in main: don\'t amend, just write better commits going forward. Perfect adherence matters less than consistent improvement.' },
  ],
}
