import type { BlogPost } from './types'

export const post: BlogPost = {
  slug: 'git-commit-best-practices',
  title: 'Git Commit Best Practices: A Practical Checklist for Developers',
  description: 'A practical, opinionated checklist of git commit best practices that actually improve code review speed and team velocity. No theory — just what works.',
  publishedAt: 'March 8, 2025',
  readTime: '7 min read',
  keywords: ['git commit best practices', 'commit message best practices', 'git workflow', 'git tips', 'better commits'],
  content: [
    { type: 'p', content: 'Most articles about commit message best practices spend too much time on theory. This one doesn\'t. Here\'s a practical checklist of what actually matters, ranked by impact.' },
    { type: 'h2', content: 'The Non-Negotiables' },
    { type: 'h3', content: '1. One logical change per commit' },
    { type: 'p', content: 'This is the single most important practice. A commit should contain one related set of changes. If your commit message needs the word "and" to describe what changed, you probably have two commits worth of work.' },
    { type: 'code', content: '# Bad: two unrelated changes in one commit\nfix(api): handle rate limiting AND update dependencies\n\n# Good: separate commits\nfix(api): handle rate limiting with exponential backoff\nchore(deps): upgrade axios to 1.6.0' },
    { type: 'h3', content: '2. Use the imperative mood' },
    { type: 'p', content: 'Write "Add login page" not "Added login page" or "Adding login page". The imperative mood reads naturally when completing the phrase: "If applied, this commit will..."' },
    { type: 'code', content: '# Imperative — correct\nAdd user authentication\nFix null pointer in payment flow\nRemove deprecated API endpoints\n\n# Past/continuous — incorrect\nAdded user authentication\nFixing null pointer in payment flow' },
    { type: 'h3', content: '3. Keep subjects under 72 characters' },
    { type: 'p', content: 'GitHub truncates at 72 characters. Many git tools truncate at 50. The subject should be a complete, meaningful sentence within those limits. If you can\'t describe the change in 72 characters, the commit is probably too large.' },
    { type: 'h2', content: 'High-Impact Practices' },
    { type: 'h3', content: '4. Explain why in the body, not what' },
    { type: 'p', content: 'The diff shows what changed. The commit body should explain why. Context that will be lost to memory in three months:' },
    { type: 'code', content: 'fix(cache): disable in-memory cache for session data\n\nThe in-memory cache caused session data to be shared between\nworker processes in PM2 cluster mode, leading to users seeing\neach other\'s data on high-traffic servers.\n\nFixes #891. Confirmed with load testing at 10x traffic.' },
    { type: 'h3', content: '5. Reference issues and PRs' },
    { type: 'p', content: 'GitHub automatically links commits to issues when you reference them. "Fixes #123" closes the issue automatically on merge. "See #456" creates a reference without closing.' },
    { type: 'code', content: 'fix(auth): handle expired session tokens gracefully\n\nFixes #234\nSee also: #198 (related token handling improvement)' },
    { type: 'h3', content: '6. Adopt Conventional Commits format' },
    { type: 'p', content: 'The type(scope): description format is the most widely adopted commit standard. It enables automatic changelog generation, semantic versioning, and makes git log scannable at a glance.' },
    { type: 'callout', content: 'CommitCraft AI generates Conventional Commits automatically from your diff. Stage your changes, click one button, and get a properly formatted message.' },
    { type: 'h2', content: 'Team Practices' },
    { type: 'h3', content: '7. Enforce format with commitlint' },
    { type: 'p', content: 'Voluntary standards drift. Automated enforcement doesn\'t. Add commitlint to your project:' },
    { type: 'code', content: 'npm install --save-dev @commitlint/cli @commitlint/config-conventional\n\n# commitlint.config.js\nmodule.exports = { extends: [\'@commitlint/config-conventional\'] }' },
    { type: 'h3', content: '8. Squash before merging feature branches' },
    { type: 'p', content: 'Feature branches accumulate "wip", "fixup", and "trying this" commits. Squash them before merging to main so the permanent history contains only meaningful commits. Most teams combine squash merging with conventional commits format for the merge commit.' },
    { type: 'h3', content: '9. Write commit messages for the person debugging at 2am' },
    { type: 'p', content: 'The primary audience for your commit messages is a developer who encounters a bug and needs to understand why code was written a certain way. They\'re probably under pressure, possibly sleep-deprived, and looking at code you wrote six months ago. Be kind to them.' },
    { type: 'h2', content: 'The Quick Reference Checklist' },
    { type: 'ol', content: [
      'One logical change per commit',
      'Subject line in imperative mood',
      'Subject under 72 characters',
      'Body explains why (not what)',
      'References related issues/PRs',
      'Uses Conventional Commits format (feat:, fix:, etc.)',
      'No "wip", "fix", "update" alone as a message',
    ]},
    { type: 'cta', content: '' },
  ],
}
